## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.6
  - 1.7
  - 1
  - nightly
notifications:
  email: false
git:
  depth: 99999999

jobs:
  include:
    - stage: "Documentation"
      julia: 1.6
      os: linux
      services:
        - docker
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
  allow_failures:
  - julia: nightly

after_success:
  # push coverage results to Codecov
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
